### ISSUE TITLE
Does not work for more than 4 variables

### ISSUE THREAD

**Issue by grosdode** [circuitpotato/truth-table-solver#1]
Does not work for more than 4 variables (Version 1 and 2 of the script):
`
Enter the number of inputs to truth table (+ve integers only): 7

Enter the truth table symbols with respect to the no. of inputs (E.g. ABCD, DCBA, aAc, cba): STUVWXY

Enter the output of truth table 0000000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0000111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0001111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0010000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0010001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010011 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010101 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010110 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0010111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0011000 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0011001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0011010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0011011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0011100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0011101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0011110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0011111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0100000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0100001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100011 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100101 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100110 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0100111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0101000 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0101001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0101010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0101011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0101100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 0101101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0101110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0101111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0110111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 0111111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1000000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1000001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000011 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000101 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000110 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1000111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1001000 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1001001 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1001010 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1001011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1001100 ('0', '1', 'x' or 'X' ) : 1
Enter the output of truth table 1001101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1001110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1001111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1010111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1011111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1100111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1101111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1110111 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111000 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111001 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111010 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111011 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111100 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111101 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111110 ('0', '1', 'x' or 'X' ) : 0
Enter the output of truth table 1111111 ('0', '1', 'x' or 'X' ) : 0

ValueError: Error from parse_expr with transformed code: "~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &~Symbol ('T' )&Symbol ('U' )&Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|~S &Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&~Symbol ('V' )&Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&~Symbol ('X' )&Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&~Symbol ('W' )&Symbol ('X' )&~Symbol ('Y' )|S &~Symbol ('T' )&~Symbol ('U' )&Symbol ('V' )&Symbol ('W' )&~Symbol ('X' )&~Symbol ('Y' )"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DGROSSKURTH\OneDrive - HBK\Desktop\truth-table-solver-main\truth_table_solver.py", line 127, in <module>
    my_simplified_expression = get_simplified_expression(my_symbols, truth_table_inputs, my_truth_table_outputs)    # get simplified boolean expression
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DGROSSKURTH\OneDrive - HBK\Desktop\truth-table-solver-main\truth_table_solver.py", line 79, in get_simplified_expression
    expression = sympify(sop_str)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\DGROSSKURTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\sympify.py", line 495, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DGROSSKURTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\parsing\sympy_parser.py", line 1087, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "C:\Users\DGROSSKURTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\parsing\sympy_parser.py", line 1078, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DGROSSKURTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\parsing\sympy_parser.py", line 906, in eval_expr
    expr = eval(
           ^^^^^
  File "<string>", line 1, in <module>
TypeError: bad operand type for unary ~: 'SingletonRegistry'
`

**Comment by circuitpotato** [comment]
Hello :) 

While debugging the code, I noticed you used the symbol 'S', which is a reserved letter in the package SymPy I use. 

Some letters that are "reserved": 
- **O:**
- **S:** reserved for 'S' class
- **I:** 
- **N:**
- **E:**
- **Q:** 

For more information: https://docs.sympy.org/latest/modules/abc.html#

**Comment by circuitpotato** [comment]
Hello :) Thank you for bringing this to my attention. I noticed you used the letter 'S' as a symbol in your inputs "STUVWXY".

'S' happens to be a reserved symbol for the package SymPy I use in Python to solve boolean algebra. I believe that might be the issue that you are facing instead of a logic issue of the code. 

Some "reserved" symbols: 
- **O:**  for big O notation
- **S:** S class
- **I:** Imaginary
- **N:** evaluates expression in floating point
- **E:** Euler's number
- **Q:** rational number 
- **For more information:** https://docs.sympy.org/latest/modules/abc.html#

I've made the necessary adjustments to the code to deal with the special letters (your current input should be able to work now). However, if you want to be very safe, you can use the likes of 'abcdefghi', up till 9 inputs.

**Comment by grosdode** [comment]
Great, thank you!

**Comment by circuitpotato** [comment]
Oops I just realised that the code issue you had was truth_table_solver version 1. The one I replied above was for **truth_table_solver2.0.** 
Anyway, I edited both versions so it should work as intended even with the reserved symbols for version 1.
